"""
Ground Truth Fact Bank — extraído manualmente da inspeção dos ContentBlocks
em PHASE 1 da auditoria RAG. Cada fato cita: material_id, block_id, page,
block_type, e a categoria (numeric|qualitative|comparative|temporal).
"""

FACT_BANK = [
    # =================== BTLG11 (material 26) ===================
    {
        "id": "BTLG_DY",
        "ticker": "BTLG11",
        "fact": "Dividend Yield 9,2%",
        "material_id": 26,
        "block_id": 102,
        "page": 2,
        "block_type": "tabela",
        "category": "numeric",
        "queries": [
            ("A", "qual o dividend yield do BTLG11?"),
            ("B", "BTLG11 tá pagando bem? quanto de DY?"),
            ("C", "qual o yield desse fundo?"),  # contexto: BTLG11
        ],
    },
    {
        "id": "BTLG_VAC",
        "ticker": "BTLG11",
        "fact": "Vacância financeira 2,9%",
        "material_id": 26,
        "block_id": 102,
        "page": 2,
        "block_type": "tabela",
        "category": "numeric",
        "queries": [
            ("A", "qual a vacância do BTLG11?"),
            ("B", "o BTLG11 tem muito espaço vazio nos imóveis?"),
            ("C", "como tá a ocupação?"),
        ],
    },
    {
        "id": "BTLG_LTV",
        "ticker": "BTLG11",
        "fact": "LTV 3,3%",
        "material_id": 26,
        "block_id": 102,
        "page": 2,
        "block_type": "tabela",
        "category": "numeric",
        "queries": [
            ("A", "qual o LTV do BTLG11?"),
            ("B", "o BTLG11 tá muito alavancado?"),
        ],
    },
    {
        "id": "BTLG_LOG",
        "ticker": "BTLG11",
        "fact": "95% dos ativos são logísticos",
        "material_id": 26,
        "block_id": 110,
        "page": 6,
        "block_type": "grafico",
        "category": "qualitative",
        "queries": [
            ("A", "qual a composição do portfólio do BTLG11 por tipo de ativo?"),
            ("B", "o BTLG11 só tem galpão ou tem outras coisas?"),
        ],
    },
    {
        "id": "BTLG_CRI",
        "ticker": "BTLG11",
        "fact": "CRI II do BTLG11 paga IPCA + 5,90% a.a. com vencimento dez-28",
        "material_id": 26,
        "block_id": 116,
        "page": 11,
        "block_type": "tabela",
        "category": "numeric",
        "queries": [
            ("A", "qual a taxa do CRI II do BTLG11?"),
            ("B", "quais CRIs o BTLG11 emitiu e a que taxa?"),
        ],
    },
    {
        "id": "BTLG_TAXA",
        "ticker": "BTLG11",
        "fact": "Taxa de administração 0,90% a.a.",
        "material_id": 26,
        "block_id": 122,
        "page": 19,
        "block_type": "texto",
        "category": "numeric",
        "queries": [
            ("A", "qual a taxa de administração do BTLG11?"),
        ],
    },
    # =================== GARE11 (material 28) ===================
    {
        "id": "GARE_GUID",
        "ticker": "GARE11",
        "fact": "Guidance de dividendos 2025: entre R$ 0,083 e R$ 0,090 por cota",
        "material_id": 28,
        "block_id": 126,
        "page": 11,
        "block_type": "texto",
        "category": "numeric",
        "queries": [
            ("A", "qual o guidance de dividendos do GARE11?"),
            ("B", "quanto o GARE11 promete distribuir?"),
        ],
    },
    {
        "id": "GARE_COTA",
        "ticker": "GARE11",
        "fact": "Cota de mercado encerrou novembro em R$ 9,24",
        "material_id": 28,
        "block_id": 127,
        "page": 12,
        "block_type": "texto",
        "category": "numeric",
        "queries": [
            ("A", "em quanto fechou a cota do GARE11 em novembro?"),
        ],
    },
    {
        "id": "GARE_XPRI",
        "ticker": "GARE11",
        "fact": "Venda de ativos para o XPRI gerou lucro bruto de R$ 145 milhões e reduziu alavancagem em R$ 356 milhões",
        "material_id": 28,
        "block_id": 124,
        "page": 9,
        "block_type": "texto",
        "category": "qualitative",
        "queries": [
            ("A", "qual foi o resultado da venda do GARE11 pro XPRI?"),
            ("B", "o GARE11 desalavancou? como?"),
        ],
    },
    # =================== MANA11 (material 36) ===================
    {
        "id": "MANA_DY",
        "ticker": "MANA11",
        "fact": "Dividend Yield 15,2% a.a.",
        "material_id": 36,
        "block_id": 223,
        "page": 3,
        "block_type": "tabela",
        "category": "numeric",
        "queries": [
            ("A", "qual o dividend yield do MANA11?"),
            ("B", "o MANA11 paga bem? quanto?"),
        ],
    },
    {
        "id": "MANA_RENT",
        "ticker": "MANA11",
        "fact": "Rentabilidade de 37,4% em 2025 (176,8% do IFIX)",
        "material_id": 36,
        "block_id": 227,
        "page": 7,
        "block_type": "texto",
        "category": "comparative",
        "queries": [
            ("A", "qual a rentabilidade do MANA11 em 2025?"),
            ("B", "o MANA11 bateu o IFIX?"),
        ],
    },
    {
        "id": "MANA_DIV",
        "ticker": "MANA11",
        "fact": "Dividendo R$ 0,11 por cota mensal (acumulado R$ 1,30 em 2025)",
        "material_id": 36,
        "block_id": 230,
        "page": 9,
        "block_type": "texto",
        "category": "numeric",
        "queries": [
            ("A", "quanto o MANA11 distribuiu por cota em 2025?"),
            ("B", "qual o dividendo mensal do MANA11?"),
        ],
    },
    {
        "id": "MANA_COTI",
        "ticker": "MANA11",
        "fact": "34.315 cotistas em dezembro/2025, crescimento de 106% no ano",
        "material_id": 36,
        "block_id": 231,
        "page": 10,
        "block_type": "texto",
        "category": "numeric",
        "queries": [
            ("A", "quantos cotistas o MANA11 tem?"),
            ("B", "a base de cotistas do MANA11 cresceu?"),
        ],
    },
    # =================== Comparativos (cross-product) ===================
    {
        "id": "CMP_BTLG_MANA",
        "ticker": None,
        "fact": "BTLG11 (DY 9,2%, vacância 2,9%, logística) vs MANA11 (DY 15,2% a.a., hedge fund)",
        "material_id": None,
        "block_id": None,
        "page": None,
        "block_type": "n/a",
        "category": "comparative",
        "queries": [
            ("A", "compara BTLG11 com MANA11"),
        ],
    },
    # =================== Negative knowledge / edge ===================
    {
        "id": "NEG_TEST11",
        "ticker": "TEST11",
        "fact": "TEST11 existe na tabela products mas não tem material indexado",
        "material_id": None,
        "block_id": None,
        "page": None,
        "block_type": "none",
        "category": "qualitative",
        "queries": [
            ("A", "me fala do TEST11"),
        ],
    },
    {
        "id": "NEG_XPTO",
        "ticker": "XPTO99",
        "fact": "Produto inexistente — não deve haver resultados",
        "material_id": None,
        "block_id": None,
        "page": None,
        "block_type": "none",
        "category": "qualitative",
        "queries": [
            ("A", "me fala do XPTO99"),
        ],
    },
]
